# Note: 192.168.123.xxx is an example network, you must update all these to match your own.

version: '2'

services:
  pihole:
    container_name: adguard
    image: adguard/adguardhome:latest
    hostname: adguard
    domainname: fbv.com.vn            # <-- Update
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      adguard_network:
        ipv4_address: 192.168.1.12   # <-- Update
    dns:
      - 127.0.0.1
      - 8.8.8.8
    restart: unless-stopped

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24            # <-- Update
          gateway: 192.168.1.1              # <-- Update
          ip_range: 192.168.1.12/30          # <-- Update
